
- name: Install new Nginx configuration
  template: src="nginx-config.tmpl" dest="/etc/nginx/sites-available/tendenci"

- name: Enable new Nginx configuration
  command: creates="/etc/nginx/sites-enabled/tendenci"
    "ln -s /etc/nginx/sites-available/tendenci /etc/nginx/sites-enabled/tendenci"

- name: Delete placeholder Nginx configuration
  command: removes="/etc/nginx/sites-enabled/default"
    "rm /etc/nginx/sites-enabled/default"

# TODO: optionally wrap this in a check so it only runs if something changed
- name: Reload Nginx so config takes effect
  service: name=tendenci state=reloaded
