
- name: Enable extensions
  postgresql_ext: db="{{ postgres_database_name }}" name="{{ item }}" state=present
  with_items:
   - postgis
   - postgis_topology
   - fuzzystrmatch
   - postgis_tiger_geocoder

