
- name: Create site superuser
  django_manage: virtualenv="{{ virtualenv_install_dir }}"  app_path="{{ website_install_dir }}"
    command="createsuperuser --username={{ superuser_username }} --email={{ superuser_email }}"
  # command: "{{ website_install_dir }}/manage.py createsuperuser --username={{ superuser_username }} --email={{ superuser_email }}"
    # executable="/usr/bin/python"

- name: Reminder!
  debug: msg="Remember to run django-admin and set a password for {{ superuser_username }}"

# FIXME: add a check for superuser pass. if its default (empty) abort.

# Looks like setting the password will need a script to be created and deleted :\
# https://docs.djangoproject.com/en/dev/topics/auth/default/#changing-passwords
# ... although perhaps I can use command to run it as a one liner

