
- name: Install Django
  pip: state=present virtualenv={{ tendenci_virtualenv_install_dir }}
    virtualenv_python='python3'
    name="{{ tendenci_django_version }}"

- name: Create directory for website
  file: state=directory path="{{ tendenci_website_install_dir }}"

- name: Create directory for logs
  file: state=directory path="{{ tendenci_website_log_dir }}" owner={{ tendenci_run_as_user }} group={{ tendenci_run_as_group }}

# Trying this http://stackoverflow.com/a/22188606; may have to go the wrapper method if it fails
# http://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/ confirms behaviour
- name: Create base website
  command: "{{ tendenci_virtualenv_install_dir }}/bin/django-admin.py startproject --template=https://github.com/tendenci/tendenci-project-template/archive/master.zip {{ tendenci_install_name }} {{ tendenci_website_install_dir }}
    creates={{ tendenci_website_install_dir }}/manage.py"

- name: Install Tendenci dependencies
  pip: state=present virtualenv={{ tendenci_virtualenv_install_dir }}
    requirements={{ tendenci_website_install_dir }}/requirements/dev.txt

# Load default theme
- name: Install default theme
  copy:
    remote_src: true
    src: "{{ tendenci_virtualenv_install_dir }}/lib/python3.6/site-packages/tendenci/themes/t7-tendenci2018/"
    dest: "{{ tendenci_website_install_dir }}/themes/tendenci2018"

# manage.py needs to be executable for django_manage to use it.
- name: Make manage.py exeutable
  file: path="{{ tendenci_website_install_dir }}/manage.py"  mode=755

- name: Initial migration
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="initial_migrate"

- name: Run deploy
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="deploy"

- name: Load theme defaults
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="load_tendenci2018_defaults"

- name: Update dashboard stats
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="update_dashboard_stats"

- name: Rebuild index
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="rebuild_index --noinput"

- name: Set site URL
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="set_setting site global siteurl {{ tendenci_server_visible_name }}"


- name: Changing website to be Read/Write by {{ tendenci_run_as_user }} and {{ tendenci_run_as_group }}
  file: owner={{ tendenci_run_as_user }} group={{ tendenci_run_as_group }} path={{ tendenci_website_install_dir }} recurse=yes

