
- name: Install Django
  pip: state=present virtualenv={{ tendenci_virtualenv_install_dir }}
    virtualenv_python='python3'
    name="{{ tendenci_django_version }}"

- name: Create directory for logs
  file: state=directory path="{{ tendenci_website_log_dir }}" owner={{ tendenci_run_as_user }} group={{ tendenci_run_as_group }}

- name: Create base website from template
  git:
    repo: "{{ tendenci_project_template }}"
    dest: "{{ tendenci_website_install_dir }}"
    update: no

- name: Install Tendenci dependencies
  pip: state=present virtualenv={{ tendenci_virtualenv_install_dir }}
    requirements={{ tendenci_website_install_dir }}/requirements/dev.txt
    extra_args="--upgrade --no-binary psycopg2"

# Load default theme
- name: Install default theme
  copy:
    remote_src: true
    src: "{{ tendenci_virtualenv_install_dir }}/lib/python3.6/site-packages/tendenci/themes/t7-tendenci2018/"
    dest: "{{ tendenci_website_install_dir }}/themes/tendenci2018"

# manage.py needs to be executable for django_manage to use it.
- name: Make manage.py exeutable
  file: path="{{ tendenci_website_install_dir }}/manage.py"  mode=755

- name: Initial migration
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="initial_migrate"

- name: Run deploy
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="deploy"

- name: Load theme defaults
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="load_tendenci2018_defaults"

- name: Update dashboard stats
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="update_dashboard_stats"

- name: Rebuild index
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="rebuild_index --noinput"

- name: Set site URL
  django_manage: virtualenv="{{ tendenci_virtualenv_install_dir }}"  app_path="{{ tendenci_website_install_dir }}"
    command="set_setting site global siteurl {{ tendenci_server_visible_name }}"

# Adjust permissions on media directories
- name: Set -x on media
  file: path="{{ tendenci_website_install_dir }}/media" mode=755
# - name: Set -x on collected
#   file: path="{{ tendenci_website_install_dir }}/manage.py" mode=755

- name: Changing website to be Read/Write by root:root
  file: owner=root group=root path={{ tendenci_website_install_dir }} recurse=yes

- name: Changing media directory properties
  file: mode=755 owner={{ tendenci_run_as_user }} group={{ tendenci_run_as_group }} path={{ tendenci_website_install_dir }}/media recurse=yes

- name: Changing static directory properties
  file: mode=755 owner={{ tendenci_run_as_user }} group={{ tendenci_run_as_group }} path={{ tendenci_website_install_dir }}/static recurse=yes

- name: Changing whoosh directory properties
  file: mode=755 owner={{ tendenci_run_as_user }} group={{ tendenci_run_as_group }} path={{ tendenci_website_install_dir }}/whoosh_index recurse=yes

