
- name: Install Django
  pip: state=present virtualenv={{ tendenci_virtualenv_install_dir }}
    virtualenv_python='python3'
    name="{{ tendenci_django_version }}"

- name: Create directory for website
  file: state=directory path="{{ tendenci_website_install_dir }}"

# Trying this http://stackoverflow.com/a/22188606; may have to go the wrapper method if it fails
# http://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/ confirms behaviour
- name: Create base website
  command: "{{ tendenci_virtualenv_install_dir }}/bin/django-admin.py startproject --template=https://github.com/tendenci/tendenci-project-template/archive/master.zip {{ tendenci_install_name }} {{ tendenci_website_install_dir }}
    creates={{ tendenci_website_install_dir }}/manage.py"

- name: Install Tendenci dependencies
  pip: state=present virtualenv={{ tendenci_virtualenv_install_dir }}
    requirements={{ tendenci_website_install_dir }}/requirements/dev.txt

- name: Changing website to be Read/Write by {{ tendenci_run_as_user }} and {{ tendenci_run_as_group }}
  file: owner={{ tendenci_run_as_user }} group={{ tendenci_run_as_group }} path={{ tendenci_website_install_dir }} recurse=yes

