---
# tasks file for tendenci

# new postgres role by ANXS doesn't seem to allow arbitrary extensions yet.
- include: configure_postgres_extensions.yml

- include: install_tendenci.yml
- include: update_local_settings_file.yml
- include: run_deploy.yml
- include: create_superuser.yml
- include: load_defaults.yml

- include: custom_themes.yml
  when: tendenci_custom_theme_name != ''

- include: configure_init_systems.yml

- include: configure_nginx.yml
  when: tendenci_perform_nginx_configuration

