
- name: Set DB connection user in settings
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: '^DATABASES.*USER'
    line: "DATABASES['default']['USER'] = '{{ tendenci_postgres_connection_user }}'"

- name: Set DB connection password in settings
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: '^DATABASES.*PASSWORD'
    line: "DATABASES['default']['PASSWORD'] = '{{ tendenci_postgres_connection_pass }}'"

- name: Set DB name in settings
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: '^DATABASES.*NAME'
    line: "DATABASES['default']['NAME'] = '{{ tendenci_postgres_database_name }}'"

- name: Set Secret key
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: "^SECRET_KEY='.+'"
    line: "SECRET_KEY='{{ tendenci_site_secret_key }}'"

- name: Set Site settings key
  lineinfile:
    path: "{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp: "^SITE_SETTINGS_KEY='.+'"
    line: "SITE_SETTINGS_KEY='{{ tendenci_site_settings_key }}'"

- name: Change log folder
  replace: name="{{ tendenci_website_install_dir }}/conf/settings.py"
    regexp="/var/log/mysite/" replace="{{ tendenci_website_log_dir }}/"

